### ISSUE TITLE
Ignore rules in yaml config

### ISSUE THREAD

**Issue by pd4d10** [dart-lang/pedantic#42]
```yml
include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
```

This would add `camel_case_types` rule.

Is there any way to ignore some rules?

**Comment by a14n** [comment]
You should be able to disable a lint with a `: false`

```yaml
include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types: false
```

See https://dart.dev/guides/language/analysis-options#disabling-individual-rules

**Comment by pd4d10** [comment]
Thanks!

**Comment by pd4d10** [comment]
Seems we should remove the `-` before items:

```yaml
include: package:pedantic/analysis_options.yaml

linter:
  rules:
    camel_case_types: false
```
