### ISSUE TITLE
Unable to use 1.9.0 on Flutter stable 1.12.13+hotfix.5

### ISSUE THREAD

**Issue by MisterJimson** [dart-lang/pedantic#46]
```
Because every version of flutter_test from sdk depends on pedantic 1.8.0+1 and beyond depends on pedantic ^1.9.0, flutter_test from sdk is forbidden.

So, because beyond depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because beyond depends on flutter_test any from sdk, version solving failed.
```
Is this intentional? We need to wait until the Flutter test SDK uses 1.9.0 before we can use it in our projects?

**Comment by davidmorgan** [comment]
This is a bug in `flutter_test`; it should not pin to exactly 1.8.0. I'll file an issue.

**Comment by dnfield** [comment]
Note that, however we slice this, you will _not_ be able to easily use the non-pinned pedantic with Flutter stable.  However, you could work around it with a dependency_override:

```yaml
name: flutter_project

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1

dependency_overrides:
  pedantic: 1.9.0
```
